Repository clasimplicio/SAP008-burger-queen-api-client, pull requests merged in 2022-12, with the labels that each got.

#53 limpeza de código e arquivos
  .eslintrc.json
  package-lock.json
  package.json
  src/App.test.js
  src/__snapshots__/App.test.js.snap
  src/components/Buttons/Button.jsx
  src/components/Buttons/ButtonComplements.jsx
  src/components/Buttons/ButtonProducts.jsx
  src/components/Buttons/Buttons.module.css
  src/components/Buttons/button.modules.css
  src/components/Header/Header.jsx
  src/components/Header/Header.module.css
  src/components/InputForm/InputForm.jsx
  src/index.css
  src/pages/kitchen/kitchen.js
  src/pages/login/login.css
  src/pages/login/login.js
  src/pages/login/login.test.js
  src/pages/menu/menu.css
  src/pages/menu/menu.js
  src/pages/menu/menu.module.css
  src/pages/orders/orders.css
  src/pages/orders/orders.js
  src/pages/register/register.css
  src/pages/register/register.js
  src/pages/register/register.test.js
  src/setupTests.js
Labels: JavaScript, React, CSS, Teste

#56 Kitchen responsiva
  .eslintrc.json
  package-lock.json
  package.json
  src/App.js
  src/App.test.js
  src/api/api.js
  src/components/Buttons/Button.jsx
  src/components/Buttons/ButtonComplements.jsx
  src/components/Buttons/ButtonProducts.jsx
  src/components/Buttons/Buttons.module.css
  src/components/Header/Header.jsx
  src/components/Header/Header.module.css
  src/components/InputForm/InputForm.jsx
  src/components/InputForm/InputForm.module.css
  src/components/Timer.jsx
  src/index.css
  src/index.js
  src/pages/kitchen/kitchen.css
  src/pages/kitchen/kitchen.js
  src/pages/login/login.css
  src/pages/login/login.js
  src/pages/login/login.test.js
  src/pages/menu/menu.css
  src/pages/menu/menu.js
  src/pages/orders/orders.css
  src/pages/orders/orders.js
  src/pages/register/register.css
  src/pages/register/register.js
Labels: CSS

#57 icone de reload
  src/components/Buttons/Button.jsx
  src/components/InputForm/InputForm.jsx
  src/pages/orders/orders.js
Labels: JavaScript, CSS

#58 trabalhando no tempo dos pedidos
  README.md
  src/components/Timer.jsx
  src/imports/imports.js
  src/pages/kitchen/kitchen.css
  src/pages/kitchen/kitchen.js
  src/pages/orders/orders.css
  src/pages/orders/orders.js
Labels: JavaScript, React

#61 contagem de tempo finalizada
  README.md
  build/asset-manifest.json
  build/index.html
  build/static/css/main.d0765355.css
  build/static/css/main.d0765355.css.map
  build/static/js/main.1e3302ad.js
  build/static/js/main.1e3302ad.js.LICENSE.txt
  build/static/js/main.1e3302ad.js.map
  src/components/Header/Header.jsx
  src/imports/imports.js
  src/pages/kitchen/kitchen.js
  src/pages/menu/menu.js
  src/pages/orders/orders.js
Labels: JavaScript, React
