Repository clasimplicio/SAP008-burger-queen-api-client, pull requests merged in 2022-11, with the labels that each got.

#11 adicionando erro no register.
  src/pages/login/login.js
  src/pages/register/register.js
Labels: help wanted, invalid

#15 Iniciando print dos produtos na tela.
  README.md
  src/api/api.js
  src/components/buttonProducts/buttonProducts.js
  src/components/user/user.js
  src/components/users/users.js
  src/pages/kitchen/kitchen.js
  src/pages/login/login.js
  src/pages/menu/menu.js
  src/pages/register/register.js
Labels: React, fetch

#17 iniciando o css do menu
  src/components/buttonProducts/buttonProducts.css
  src/components/buttonProducts/buttonProducts.js
  src/components/header/header.css
  src/components/header/headerAdmin.js
  src/components/header/headerKitchen.js
  src/components/header/headerService.js
  src/components/selectMenu/selectMenu.css
  src/components/selectMenu/selectMenu.js
  src/index.css
  src/pages/login/login.css
  src/pages/login/login.js
  src/pages/menu/menu.css
  src/pages/menu/menu.js
  src/pages/register/register.css
Labels: design, React

#20 uma arrumada nos componentes, Input dos forms criado.
  src/components/ButtonProducts/ButtonProducts.css
  src/components/ButtonProducts/ButtonProducts.js
  src/components/ButtonSendKitchen/ButtonKitchen.css
  src/components/ButtonSendKitchen/ButtonKitchen.js
  src/components/ButtonSignin/ButtonSignin.css
  src/components/ButtonSignin/ButtonSignin.js
  src/components/Header/Header.css
  src/components/Header/HeaderAdmin.js
  src/components/Header/HeaderKitchen.js
  src/components/Header/HeaderService.js
  src/components/InputForm/InputForm.css
  src/components/InputForm/InputForm.js
  src/components/SelectMenu/SelectMenu.css
  src/components/SelectMenu/SelectMenu.js
  src/components/User/User.js
  src/components/Users/Users.js
  src/components/buttonProducts/buttonProducts.js
  src/index.css
  src/pages/admin/admin.js
  src/pages/kitchen/kitchen.js
  src/pages/login/login.css
  src/pages/login/login.js
  src/pages/menu/menu.js
  src/pages/orders/orders.js
  src/pages/register/register.css
  src/pages/register/register.js
Labels: React, CSS

#25 header em um só arquivo.
  src/api/main.js
  src/components/Buttons/ButtonProducts.jsx
  src/components/Buttons/ButtonProducts.module.css
  src/components/Buttons/SelectMenu.module.css
  src/components/Header/Header.jsx
  src/components/Header/Header.module.css
  src/components/Header/HeaderAdmin.jsx
  src/components/Header/HeaderKitchen.jsx
  src/components/Header/HeaderService.jsx
  src/pages/admin/admin.js
  src/pages/kitchen/kitchen.js
  src/pages/menu/menu.js
  src/pages/menu/menu.module.css
  src/pages/orders/orders.js
Labels: React, CSS

#28 Add/remover itens no carrinho.
  src/api/api.js
  src/api/main.js
  src/components/Buttons/ButtonProducts.jsx
  src/components/itemInCar/item.jsx
  src/pages/admin/admin.js
  src/pages/admin/componentes/AddUser.jsx
  src/pages/admin/componentes/User.jsx
  src/pages/admin/componentes/Users.jsx
  src/pages/menu/menu.js
  src/pages/register/register.js
Labels: JavaScript, React

#30 arquivos de componentes organizado e teste register
  src/App.test.js
  src/api/api.js
  src/components/Buttons/ButtonKitchen.jsx
  src/components/Buttons/ButtonKitchen.module.css
  src/components/Buttons/ButtonProducts.jsx
  src/components/Buttons/ButtonProducts.module.css
  src/components/Buttons/ButtonSignin.jsx
  src/components/Buttons/ButtonSignin.module.css
  src/components/Buttons/Buttons.jsx
  src/components/Buttons/Buttons.module.css
  src/components/Buttons/SelectMenu.jsx
  src/components/Buttons/SelectMenu.module.css
  src/components/Header/Header.jsx
  src/components/Header/Header.module.css
  src/index.css
  src/pages/login/login.js
  src/pages/login/login.test.js
  src/pages/menu/menu.js
  src/pages/menu/menu.module.css
  src/pages/register/register.js
  src/pages/register/register.test.js
  src/setupTests.js
Labels: Teste

#32 alterações no css(tablet) de login/register/menu
  src/App.js
  src/components/Buttons/Buttons.module.css
  src/components/Header/Header.module.css
  src/components/InputForm/InputForm.module.css
  src/components/itemInCar/item.jsx
  src/components/itemInCar/item.module.css
  src/index.css
  src/pages/menu/menu.js
  src/pages/menu/menu.module.css
  src/pages/register/register.css
Labels: CSS

#33 Add quantidade ao objeto do carrinho.
  src/components/Buttons/Buttons.module.css
  src/components/itemInCar/item.jsx
  src/components/itemInCar/item.module.css
  src/pages/admin/admin.js
  src/pages/admin/componentes/AddUser.jsx
  src/pages/admin/componentes/User.jsx
  src/pages/admin/componentes/Users.jsx
  src/pages/admin/user.jsx
  src/pages/admin/user.module.css
  src/pages/menu/menu.js
  src/pages/menu/menu.module.css
  src/setupTests.js
Labels: JavaScript, React

#35 Itens carrinho
  src/components/Buttons/Buttons.module.css
  src/components/Header/Header.module.css
  src/index.css
  src/pages/login/login.css
  src/pages/menu/menu.js
  src/pages/menu/menu.module.css
Labels: JavaScript, CSS

#36 Add funcao de soma do carrinho.
  src/components/Buttons/Buttons.jsx
  src/components/Buttons/Buttons.module.css
  src/components/Header/Header.module.css
  src/pages/admin/admin.js
  src/pages/login/login.js
  src/pages/menu/menu.js
  src/pages/menu/menu.module.css
  src/pages/orders/orders.css
  src/pages/orders/orders.js
  src/pages/orders/orders.module.css
  src/pages/register/register.js
Labels: JavaScript, React

#37 erros direto da API no register
  src/pages/login/login.css
  src/pages/login/login.js
  src/pages/register/register.css
  src/pages/register/register.js
Labels: JavaScript, CSS

#41 construção da página de pedidos.
  README.md
  src/components/Buttons/Buttons.module.css
  src/pages/admin/admin.js
  src/pages/menu/menu.js
  src/pages/orders/orders.js
  src/pages/orders/orders.module.css
Labels: JavaScript, CSS

#44 o icone - excluindo quando chega em 0
  src/components/Buttons/Buttons.jsx
  src/pages/menu/menu.js
Labels: JavaScript

#46 Orders
  build/asset-manifest.json
  build/index.html
  build/static/css/main.d0765355.css
  build/static/css/main.d0765355.css.map
  build/static/js/main.1e3302ad.js
  build/static/js/main.1e3302ad.js.LICENSE.txt
  build/static/js/main.1e3302ad.js.map
  build/static/media/burger.c530d6a1e09583b325e8.png
  build/static/media/ovo.0dbc991a078ba6fdc64c.png
  build/static/media/queijo.7de35575c9fbbba1e18d.png
  src/App.test.js
  src/__snapshots__/App.test.js.snap
  src/api/api.js
  src/pages/admin/admin.js
  src/pages/kitchen/kitchen.js
  src/pages/menu/menu.js
  src/pages/orders/orders.js
  src/pages/register/register.js
  src/setupTests.js
Labels: JavaScript, React, fetch

#48 logout
  src/components/Header/Header.jsx
  src/components/Header/Header.module.css
Labels: JavaScript, React

#50 limpeza de arquivos e componentes
  src/App.js
  src/api/api.js
  src/api/main.js
  src/assets/burger-simple-chicken.png
  src/assets/burger-simple-vegan.png
  src/assets/burger-simple.png
  src/assets/coffee-cup.png
  src/assets/double-burger-chicken.png
  src/assets/double-burger-vegan.png
  src/assets/double-burger.png
  src/assets/french-fries.png
  src/assets/milk-coffee.png
  src/assets/onion-ring.png
  src/assets/orange-juice.png
  src/assets/sandwich.png
  src/assets/soda.png
  src/assets/water.png
  src/components/Buttons/Button.jsx
  src/components/Buttons/Buttons.jsx
  src/components/Buttons/Buttons.module.css
  src/components/Buttons/button.modules.css
  src/pages/admin/admin.js
  src/pages/admin/user.jsx
  src/pages/admin/user.module.css
  src/pages/kitchen/kitchen.js
  src/pages/login/login.js
  src/pages/menu/menu.js
  src/pages/menu/menu.module.css
  src/pages/orders/orders.js
  src/pages/register/register.js
Labels: JavaScript, React, CSS
